### ISSUE TITLE
[Lib & Tools]

### ISSUE THREAD

**Issue by Sphinxes0o0** [Sphinxes0o0/notes#11]
http://recursos.aldabaknocking.com/libpcapHakin9LuisMartinGarcia.pdf

**Comment by 4soos** [comment]
check this tutorial:

https://github.com/vichargrave/sniffer/blob/master/sniffer.c#L116

**Comment by Sphinxes0o0** [comment]
https://github.com/lixiaolia/ndk-someiplib

**Comment by Sphinxes0o0** [comment]
> check this tutorial is ok or not on linux:
> 
> https://github.com/vichargrave/sniffer/blob/master/sniffer.c#L116

DONE
