### ISSUE TITLE
[BSD][kernel]mbuf 

### ISSUE THREAD

**Issue by Sphinxes0o0** [Sphinxes0o0/notes#14]
https://www.bsdcan.org/2004/papers/NetworkBufferAllocation.pdf

**Comment by 4soos** [comment]
https://github.com/freebsd/freebsd-src/blob/main/usr.bin/netstat/mbuf.c#L70

**Comment by 4soos** [comment]
> https://github.com/freebsd/freebsd-src/blob/main/usr.bin/netstat/mbuf.c#L70

这个代码太新了不适合在QNX上面使用， qnx上面支持使用sysctl MIB的方式获取一些kern 的信息：

https://www.qnx.com/developers/docs/7.0.0/#com.qnx.doc.neutrino.lib_ref/topic/s/sysctl.html

进一步的阅读可以看这个：
https://man.freebsd.org/cgi/man.cgi?sysctl(3)

TODO:
写一个像netstat -m 的小工具， 可以获取kern的mbuf信息， 同时监控一下使用

**Comment by 4soos** [comment]
https://www.qnx.com/developers/docs/7.0.0/index.html#com.qnx.doc.neutrino.utilities/topic/s/sysctl.html

**Comment by 4soos** [comment]
> > https://github.com/freebsd/freebsd-src/blob/main/usr.bin/netstat/mbuf.c#L70
> 
> 这个代码太新了不适合在QNX上面使用， qnx上面支持使用sysctl MIB的方式获取一些kern 的信息：
> 
> https://www.qnx.com/developers/docs/7.0.0/#com.qnx.doc.neutrino.lib_ref/topic/s/sysctl.html
> 
> 进一步的阅读可以看这个： https://man.freebsd.org/cgi/man.cgi?sysctl(3)
> 
> TODO: 写一个像netstat -m 的小工具， 可以获取kern的mbuf信息， 同时监控一下使用

还是要多看书 多学习

**Comment by Sphinxes0o0** [comment]
看看FreeBSD 实现里面有没有这个mbuf 的资料吧
