### ISSUE TITLE
[linux]sysctl 

### ISSUE THREAD

**Issue by Sphinxes0o0** [Sphinxes0o0/notes#16]
https://man7.org/linux/man-pages/man2/sysctl.2.html

**Comment by 4soos** [comment]
https://www.qnx.com/developers/docs/7.1/#com.qnx.doc.neutrino.lib_ref/topic/s/sysctl.html

**Comment by Sphinxes0o0** [comment]
QNX done.
Android : TODO
[QNX sysctl 参数整理 v0.1.docx](https://github.com/Sphinxes0o0/notes/files/13363489/QNX.sysctl.v0.1.docx)
[sysctl.zip](https://github.com/Sphinxes0o0/notes/files/13363496/sysctl.zip)

**Comment by Sphinxes0o0** [comment]
Android DONE
