### ISSUE TITLE
[Socket] routing socket

### ISSUE THREAD

**Issue by Sphinxes0o0** [Sphinxes0o0/notes#7]
- BSD
- Linux

**Comment by 4soos** [comment]
https://github.com/openbsd/src/blob/master/sbin/route/route.c#L1138

**Comment by 4soos** [comment]
https://github.com/freebsd/freebsd-src/blob/main/sbin/route/route.c

**Comment by 4soos** [comment]
http://blog.chinaunix.net/uid-25324849-id-213709.html

**Comment by 4soos** [comment]
https://megahertz66.github.io/kernel/2020/11/12/netlink-0/

**Comment by 4soos** [comment]
http://blog.chinaunix.net/uid-25324849-id-214912.html 

路由 netlink

**Comment by 4soos** [comment]
> ~http://blog.chinaunix.net/uid-25324849-id-214912.html~
> 
> ~路由 netlink~

checked

**Comment by 4soos** [comment]
~> http://blog.chinaunix.net/uid-25324849-id-213709.html~
checked

**Comment by 4soos** [comment]
~> https://megahertz66.github.io/kernel/2020/11/12/netlink-0/~

checked

**Comment by Sphinxes0o0** [comment]
https://github.com/boundary/libdnet
